name: bookia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/svg/

fonts:
  - family: DMSerif
    fonts: 
      - assets: assets/fonts/DMSerifDisplay-Regular.ttf